detector_nodes:
# Keep in mind to tab-align the values!!!!
# The name of the detector MUST be the same as the field inside the DetectionArray message!
  - 
    name:           "body"
    weight:         1
    min_detections: 1
    min_frequency:  2
    topic:          "/people_detections/body_detections"
  - 
    name:           "face"
    min_detections: 1
    weight:         1
    min_frequency:  2
    topic:          "/people_detections/face_detections"
  - 
    name:           "laser"
    min_detections: 1
    weight:         1
    min_frequency:  2
    topic:          "/people_detections/laser_detections"
time_horizon_sec: 5.4
